### ISSUE TITLE
빛토마토 로고제작

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitTomato#1]
빛토마토 로고 제작
AI 이미지 생성 + magick 도구 활용

**Comment by choonghyunryu** [comment]
@statkclee,

멋지네요.
그런데, Hex 로고 테두리가 너무 거친데, 수정 가능할까요?
안티-알리아싱이 필요해 보입니다.

**Comment by choonghyunryu** [comment]
와우 멋지네요. 
짝짝짝!!
