### ISSUE TITLE
title, contents 텍스트 HTML Unescape

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitTomato#11]
title, contents 텍스트에 HTML Unescape를 하여 title, contents 텍스트를 깔끔하게 정리할 필요가 있습니다.
그리고 탭 혹은 공백 2개 이상 되는 텍스트도 제거가 필요해보입니다.

```
unescape_html <- function(str){
  xml2::xml_text(xml2::read_html(paste0("<x>", str, "</x>")))
}

tomato |> 
  mutate(contents = map_chr(contents, unescape_html),
         title    = map_chr(title, unescape_html))
```

반영전
<img width="623" alt="image" src="https://github.com/bit2r/bitTomato/assets/5325425/607fdc27-6a2e-43e5-8c0b-a7dfab386c16">

반영후
![image](https://github.com/bit2r/bitTomato/assets/5325425/c6f34dbc-3a4f-46c2-abda-8e18bf4d22e3)

**Comment by choonghyunryu** [comment]
@statkclee,

감사합니다.
content 컬럼을 설명할 때, "어느 정도 정제된"이라는 표현을 썼었는데,
이 정도는 전처리해서 쓰라는 의도가 내포되어 있었습니다. 학습 측면에서...

학습이 아닌 실 사용자를 위한 배려가 부족한 것 같았습니다. T,.T

지적해주신 것과 아울러, postfix에 기자 이름과 이메일 주소도 제거했습니다.

```
  mutate(contents = str_remove_all(contents, "\\[[[:print:]]*\\]\\s*|&\\w+;")) |>
  mutate(contents = str_remove(contents, "\\w+ 기자 [0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}")) |>
  mutate(contents = str_squish(contents)) 
```

정제된 데이터셋을 다시 올려 놓겠습니다.

**Comment by choonghyunryu** [comment]
0.2.0.9000 버전에 반영
