### ISSUE TITLE
대량의 결측치 점검 요청

### ISSUE THREAD

**Issue by jowoncni1** [bit2r/bitTomato#16]
> # 전체 데이터셋에서 NA값이 있는지 확인
> any(is.na(tomato))
[1] TRUE
> 
> # 결측치가 있는 행들만 따로 모아서 데이터프레임화
> tomato_na <- tomato[!complete.cases(tomato), ]
> 
> tomato_na
# A tibble: 434 × 7
   title                          url   contents author create_dt           category subcategory
   <chr>                          <chr> <chr>    <chr>  <dttm>              <chr>    <chr>      
 1 국내 코로나19 확진-사망 변화 … http… NA       권새나 2020-03-11 10:18:00 사회     코로나19(… 
 2 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-12 10:24:00 사회     코로나19(… 
 3 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-13 10:27:00 사회     코로나19(… 
 4 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-16 10:27:00 사회     코로나19(… 
 5 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-17 10:17:00 사회     코로나19(… 
 6 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-18 10:18:00 사회     코로나19(… 
 7 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-19 10:18:00 사회     코로나19(… 
 8 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-20 10:14:00 사회     코로나19(… 
 9 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-22 14:31:00 사회     코로나19(… 
10 국내 코로나19 확진-사망 현황 … http… NA       권새나 2020-03-24 10:28:00 사회     코로나19(… 
# ℹ 424 more rows
# ℹ Use `print(n = ...)` to see more rows
> # 각 열별로 NA 값이 몇 개 있는지 확인
> colSums(is.na(tomato))
      title         url    contents      author   create_dt    category subcategory 
          0           0         425           9           0           0           0 
>

**Comment by choonghyunryu** [comment]
@jowoncni1,

감사합니다.
본문 결측치 건 데이터에서 필터링하겠습니다.

**Comment by choonghyunryu** [comment]
0.3.1 버전에서 fix
